// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name  string `json:"name"`
	Class int    `json:"class"`
}

type User struct {
	ID    string `json:"_id" bson:"_id"`
	Name  string `json:"name"`
	Class int    `json:"class"`
}
